:Author: Summit Innovations
:Email: frysamuel6@gmail.com
:Date: 01/15/2026
:Revision: version#0.3
:License: Public Domain

= Project: Summit Hearing 0.1

IoT project designed to help mixed deaf households communicate when out of sight. JitterBug offers communication between two devices - a mother and child device -, vibrating when a transmission is sent. The project uses an XIAO ESP32 C3 as the child device and a digital app as the mother device. When a click is made, a signal will be send to the microcontroller, initiating a buzz on a coin-vibrator. A signal can be sent back via a push button, indicating that the message was received and the child device is moving towards the mother device. 


== Step 1: Installation
Please describe the steps to install this project.

1. Attach a 3.3V battery to the microcontroller. 
2. Keep the mother and child device within 25 feet of eachother when communicating

== Step 2: Assemble the circuit

SCHEMATIC IS FORTHCOMING

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]

=== Changelog
- 1/13/2026 Arduino MKR WiFi 1010 was received 
- 1/14/2026 Arduino MKR WiFi 1010 was configured
- 1/15/2026 Arduino MKR WiFi 1010 is able to sent digital pulses to LED
- 1/16/2026 Arduino MKR WiFi 1010 connected successfully to the internet
- 1/17/2026 Arduino MKR WiFi 1010 is battery-powered and disconnected from the computer USB
- 1/20/2026 Arduino MKR WiFi 1010 successfully outputted voltage to vibration motor
- 1/21/2026 Implemented button logic to light up an LED
- 1/23/2026 Attached Thing to ESP32S3
- 1/27/2026 ESP32S3 added battery functionality
- 1/27/2026 Put in housing for further testing
- 1/30/2026 Added LED_PIN functionality for led blink
- 2/2/2026 Made Thing unique to prototype (Rev 6)
- 2/13/2026 Added App functionality and global variable
- 2/26/2026 Made Revision 7, making device smaller with smaller battery. Similar functionality though.
- 3/4/2026 Made Revision 8, connecting device to Firebase
- 3/16/2026 Made Revision 9, connecting device to App and creating app logic
- 3/18/2026 Finished defining finite states for app and microcontroller, optimized button functionality and socket connection polling
- 3/20/2026 Shifted to new prototype (Ripple Glasses)
- 4/8/2026 Completed Rev 1.3, able to capture sound bites 5 seconds in length
