// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define BUTTON_PIN 8
#define BUZZER_PIN 6
#define LED_PIN 7

typedef enum {UP=0, DOWN, PRESS, RELEASE} ButtonState;

ButtonState current_state = UP;
ButtonState past_state = UP;

const char DEVICE_LOGIN_NAME[]  = "3dabd68e-de6b-4b71-980b-18357ee4a025";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password



void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
